version: '3'
services:
  app:
    build: .
    ports:
      - '8000:8000'
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb+srv://hassanoladipupo:root@hassanoladipupo.vdfhcxr.mongodb.net/E-commerce-storeDB
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  mongo-express:
    image: mongo-express:latest
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: hassanoladipupo
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: hassanoladipupo.vdfhcxr.mongodb.net
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
